// Build definition for the mubit-memory Codex plugin.
//
// It mirrors `../claude-code/esbuild.config.mjs` deliberately — same settings, same
// launcher/impl split, same byte-reproducibility pins — because the two plugins are built
// from one source tree and CI rebuilds both and runs `git diff --exit-code`. Where this file
// differs from its sibling, the difference is a fact about Codex and is commented as one.
//
// What every target here has in common: the entry point is a two-line file under
// `hooks/src/`, and what it pulls in is `../claude-code/hooks/src/<name>.mjs` and the whole
// of `../claude-code/lib/`. esbuild inlines all of it, so a shipped Codex bundle contains no
// reference to a sibling directory that a marketplace install would not have copied.

import { copyFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SHARED = resolve(ROOT, '..', 'claude-code');

/**
 * esbuild, resolved out of the sibling plugin's `node_modules`.
 *
 * A bare `import { build } from 'esbuild'` walks up from this file and finds nothing: this
 * package has no `node_modules` of its own, and the repo root has none either. The sibling
 * does, and it is the same version — `package.json` here declares the same `^0.28.0` so the
 * dependency is stated rather than smuggled.
 *
 * The alternative was a `node_modules` symlink to the sibling, which works and is invisible:
 * it is untracked, so a fresh clone has no build at all and the error names a missing package
 * rather than a missing symlink. Resolving explicitly makes the coupling something you can
 * read, and the failure below says exactly what to do about it.
 */
const require = createRequire(import.meta.url);
let esbuild;
try {
  esbuild = await import(pathToFileURL(require.resolve('esbuild', { paths: [SHARED, ROOT] })).href);
} catch {
  console.error(
    '[esbuild] cannot resolve esbuild.\n'
    + '  The Codex plugin builds with the sibling plugin`s copy — the two are built from one\n'
    + '  source tree and pin the same version. Install it there:\n'
    + `      npm --prefix ${SHARED} install\n`
    + '  (Do NOT run `npm run verify` or `npm run clean` in that directory: its `clean` deletes\n'
    + '  mcp/dist/server.js, which is vendored and cannot be rebuilt in this checkout.)');
  process.exit(1);
}
const { build, context } = esbuild;
const has = (rel) => existsSync(resolve(ROOT, rel));

// Where the build WRITES; inputs always come from `ROOT`. Same knob, same reason, as the
// sibling's: the freshness gate rebuilds into a temp directory and compares byte-for-byte with
// what is committed, because `npm test` runs `hooks/src` and Codex runs `hooks/dist`.
const OUT = process.env.MUBIT_CC_BUILD_OUTDIR ? resolve(process.env.MUBIT_CC_BUILD_OUTDIR) : ROOT;

// The publish build. `sourcemap: 'inline'` embeds `sourcesContent` — the full text of every
// module esbuild pulled in — and here that is the whole of the *sibling's* `lib/` and
// `hooks/src/`, which `package.json`'s `files` does not publish. Releasing without this set
// ships that source base64'd inside files that are on the published list, where neither grep
// nor a diff will show it. The sibling grew the same flag at `c768465`; this is that flag.
const NO_SOURCEMAP = process.env.MUBIT_CC_BUILD_NO_SOURCEMAP === '1';
const out = (rel) => resolve(OUT, rel);
const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

const shared = {
  bundle: true, platform: 'node', target: 'node20', format: 'esm',
  minify: false,            // readable stack traces beat 40 KB; nothing ships over a network
  sourcemap: NO_SOURCEMAP ? false : 'inline', legalComments: 'none', logLevel: 'info',
  banner: { js: '// mubit-memory (Codex) — generated by esbuild. Do not edit; edit integrations/codex/hooks/src, integrations/codex/lib, or the shared integrations/claude-code sources.' },
};

// The eleven Codex registrations need eight of these; `drain`, `recall-refresh` and
// `session-resume` are spawned detached and exec'd by path, so they need the same launcher
// and runtime floor. `session-resume` is only reachable through the shared `session-start`
// body, and without a bundle here `spawnDetached` would resolve nothing and the W2-2 briefing
// would be a silent no-op on this host alone.
//
// `cwd-changed` is deliberately absent. Codex has no `CwdChanged` event, so building it would
// ship a bundle nothing can ever invoke — and `manifests`-style tests that check every
// registration against `hooks/dist/` cannot catch a bundle with no registration.
const HOOKS = [
  'session-start', 'prompt-recall', 'stage-prompt', 'pre-tool', 'subagent-start',
  'capture', 'checkpoint', 'session-end', 'drain', 'recall-refresh', 'session-resume',
];

/**
 * The vendored MCP server bundle, copied rather than rebuilt.
 *
 * Two independently installable plugins cannot share a path: a Codex marketplace install
 * copies the plugin directory into `$CODEX_HOME/plugins/cache/…`, where `../claude-code`
 * does not exist. So this plugin carries its own copy, and the duplicate 5.9 MB is the cost
 * of the second plugin.
 *
 * It is **copied**, not regenerated, and that is what lets `codex-mcp.test.mjs` assert the
 * two are byte-identical rather than merely equivalent. Regenerating would also require the
 * `../mcp` TypeScript sibling, which does not exist in the generated `claude-plugins` mirror
 * this tree lives in.
 */
const VENDORED_SERVER = resolve(SHARED, 'mcp', 'dist', 'server.js');

/** The version stamped into the launcher as `__MUBIT_MCP_VERSION__`; see the sibling config. */
const MCP_VERSION = existsSync(resolve(SHARED, '..', 'mcp', 'package.json'))
  ? readJson(resolve(SHARED, '..', 'mcp', 'package.json')).version
  : readJson(resolve(ROOT, 'package.json')).version;

// ---------------------------------------------------------------------------
// The runtime floor guard
// ---------------------------------------------------------------------------
// Identical in shape and reason to the sibling's, and one degree more necessary here: Codex
// runs a hook command through `$SHELL -lc`, so the `node` a hook gets is whatever a login
// shell resolves — not the one that started Codex, and not necessarily one that can parse
// `??`. On an older Node the bundles do not fail, they never load, and say nothing: no
// marker, no log line, no MCP activity, which reads exactly like a plugin that was never
// configured. A guard inside the bundle cannot help, because a module is parsed in full
// before its first statement runs.
//
// So the file the registration names is this launcher, built for an old runtime, and the real
// bundle lives in `impl/`.
const MIN_NODE_MAJOR = 20;
const LAUNCHER_TARGET = 'node12.20';   // >= 12.20, or esbuild rewrites import() into require()

// `{}`, where the sibling's launcher writes `{"suppressOutput":true}`. This is the one place
// the two guards differ, and it is a fact about Codex.
//
// Codex rejects `suppressOutput` at parse time on PreToolUse, PostToolUse and
// PermissionRequest, and shows `• PostToolUse hook (failed)` in place of whatever the hook
// said. Both branches below exist to put a diagnostic in front of the user, and both were
// destroying it — on the two paths where a diagnostic is the only thing still working.
//
// It cannot be fixed downstream. The launcher writes this *before* `impl/` loads, so it never
// reaches `lib/hook.mjs` and the `forHost()` filter never sees it. `{}` satisfies all ten
// output schemas (not one has a required property) and breaks no rule in
// `test/fixtures/codex-output-rules.json`.
//
// stdout stays JSON either way: Codex injects non-JSON stdout into the model's context as
// developer context, so the diagnostic goes to stderr and stdout carries only this.
const QUIET_OK = "'{}'";

const launcher = (rel, what) => `import { writeSync } from 'fs';
var major = parseInt(String(process.versions.node).split('.')[0], 10);
if (!(major >= ${MIN_NODE_MAJOR})) {
  try {
    writeSync(2, 'mubit-memory requires Node >= ${MIN_NODE_MAJOR} (package.json engines); found v'
      + process.versions.node + '. ${what} is disabled for this session.\\n');
    writeSync(1, ${QUIET_OK});
  } catch (e) { /* a closed pipe is not worth failing a session over */ }
  // 0, never 1: Codex reads a non-zero exit as a hook error, and 2 as a block.
  process.exit(0);
}
globalThis.__mubitLauncherEntry = ${JSON.stringify(rel)};
import('${rel}').catch(function (err) {
  try {
    writeSync(2, 'mubit-memory: ${what} failed to load: '
      + ((err && err.message) ? err.message : String(err)) + '\\n');
    writeSync(1, ${QUIET_OK});
  } catch (e) { /* ditto */ }
  process.exit(0);
});
`;

const launcherTarget = (contents, sourcefile, outfile) => ({
  stdin: { contents, sourcefile, loader: /** @type {const} */ ('js'), resolveDir: ROOT },
  outfile: out(outfile),
  bundle: false,              // the one dynamic import must stay a runtime import, not inlined
  platform: /** @type {const} */ ('node'),
  format: /** @type {const} */ ('esm'),
  target: LAUNCHER_TARGET,
  minify: false, legalComments: /** @type {const} */ ('none'), logLevel: /** @type {const} */ ('info'),
  banner: { js: '// mubit-memory (Codex) runtime floor guard — generated by esbuild. Do not edit.' },
});

const targets = [
  // outExtension is load-bearing: with `outdir`, esbuild names output `<entry>.js` whatever
  // the entry was called, so `capture.mjs` would become `capture.js` while `hooks.json` names
  // `capture.mjs`. Every hook silently becomes a dead path.
  {
    entryPoints: HOOKS.map((n) => `hooks/src/${n}.mjs`),
    outdir: out('hooks/dist/impl'), outbase: 'hooks/src',
    outExtension: { '.js': '.mjs' },
    ...shared,
  },
  ...HOOKS.map((n) => launcherTarget(
    launcher(`./impl/${n}.mjs`, `hook ${n}`), `${n}.launcher.mjs`, `hooks/dist/${n}.mjs`,
  )),
  // The auth binary. `/mubit-memory:auth` is the one skill that calls no MCP tool — it runs
  // this to obtain the credential every other tool needs — so a Codex plugin without it has
  // no first-run story at all.
  { entryPoints: [resolve(SHARED, 'bin', 'auth.src.mjs')], outfile: out('bin/auth.mjs'), ...shared },
  // The activity binary. The `activity` skill ships under both hosts and its only instruction
  // is to run this file, so without the target the Codex copy of the skill names a path that
  // does not exist — the same first-run dead end `auth` would have.
  { entryPoints: [resolve(SHARED, 'bin', 'activity.src.mjs')], outfile: out('bin/activity.mjs'), ...shared },
  // The pin binary, from the same shared source as the Claude Code copy. `/mubit-memory:pin`
  // is the second skill that calls no MCP tool — the vendored server has no variables tool to
  // call — so without this the skill on this host names a binary that does not exist.
  { entryPoints: [resolve(SHARED, 'bin', 'pin.src.mjs')], outfile: out('bin/pin.mjs'), ...shared },
  // The admin binary, from the same shared source. The four skills that call it ship under
  // both hosts, so without this target the Codex copies name a path that does not exist.
  { entryPoints: [resolve(SHARED, 'bin', 'admin.src.mjs')], outfile: out('bin/admin.mjs'), ...shared },
  // `/mubit-memory:import`, the transcript backfill. Shared source, same as every other
  // binary here: the transcripts it reads are Claude Code's, and a Codex user with both
  // installed has the same history to import.
  { entryPoints: [resolve(SHARED, 'bin', 'import.src.mjs')], outfile: out('bin/import.mjs'), ...shared },
  // `/mubit-memory:handoff`, from the same shared source; the Codex skill names this path.
  { entryPoints: [resolve(SHARED, 'bin', 'handoff.src.mjs')], outfile: out('bin/handoff.mjs'), ...shared },
  // The dashboard binary, built from the same shared source as the Claude Code copy. Two
  // installable plugins cannot share a path — the same reason this tree carries its own
  // `mcp/dist/server.js` — so the bundle is emitted here rather than referenced across.
  //
  // `bin/dashboard.html` is *not* an entry point: the server reads it at runtime as a sibling
  // of the bundle, which keeps `bin/dashboard.src.mjs` loadable by Node for the suite and keeps
  // 42 KB of markup out of the inline sourcemap. It ships as the tracked copy in this `bin/`.
  { entryPoints: [resolve(SHARED, 'bin', 'dashboard.src.mjs')], outfile: out('bin/dashboard.mjs'), ...shared },
  // No status line target. Codex's status line is a declarative list of built-in item ids:
  // there is no command hook and nothing scriptable to render into, so `bin/statusline.mjs`
  // here would be dead weight in every marketplace bundle. `lib/config.mjs` defaults
  // `statusLine` to false under this host for the same reason.
  {
    entryPoints: [resolve(SHARED, 'mcp', 'src', 'launch.mjs')],
    outfile: out('mcp/dist/index.js'),
    ...shared,
    external: ['./server.js'],
    define: { __MUBIT_MCP_VERSION__: JSON.stringify(MCP_VERSION) },
  },
];

// Entry points that have not been written yet are skipped with a warning rather than failing
// the build, which is what keeps `npm run build` usable while the port lands. A missing bundle
// is already caught by `codex-manifests.test.mjs`, which checks every registration in
// `hooks.json` against `hooks/dist/`.
const runnable = [];
for (const t of targets) {
  if (!t.entryPoints) { runnable.push(t); continue; }
  const present = t.entryPoints.filter((e) => (e.startsWith('/') ? existsSync(e) : has(e)));
  for (const missing of t.entryPoints.filter((e) => !(e.startsWith('/') ? existsSync(e) : has(e)))) {
    console.warn(`[esbuild] skipping ${missing} — not written yet`);
  }
  if (present.length) runnable.push({ ...t, entryPoints: present });
}

const watch = process.argv.includes('--watch');
for (const t of runnable) { if (watch) { (await context(t)).watch(); } else { await build(t); } }

// The server bundle, copied last so a failed build never leaves a half-updated pair.
//
// Refusing rather than skipping when the source is absent, for the same reason the sibling
// refuses to skip its server target: skipping leaves the committed copy in place, and the
// CI gate that rebuilds and runs `git diff --exit-code` then passes while never having
// touched the file — a green build that proves nothing, in exactly the place a stale server
// bundle already shipped once.
if (!existsSync(VENDORED_SERVER)) {
  console.error(
    `[esbuild] ${VENDORED_SERVER} does not exist.\n`
    + '  The Codex plugin copies the Claude Code plugin`s vendored MCP server bundle rather\n'
    + '  than rebuilding it — two installable plugins cannot share a path, and this tree has\n'
    + '  no ../mcp TypeScript sibling to build from.\n'
    + '  Build the sibling plugin first, or restore its committed mcp/dist/server.js.');
  process.exit(1);
}
mkdirSync(out('mcp/dist'), { recursive: true });
copyFileSync(VENDORED_SERVER, out('mcp/dist/server.js'));
console.log('[esbuild] copied mcp/dist/server.js from the shared plugin');

// The dashboard's page, copied for the same reason and on the same terms as the server bundle
// above: `bin/dashboard.mjs` reads it at runtime as a sibling of itself, two installable
// plugins cannot share a path, and a hand-maintained second copy is a UI that drifts from the
// one the tests cover. Copying it makes the codex copy build output rather than a tracked
// duplicate, so `codex-dist.test.mjs` catches divergence instead of tolerating it.
const SHARED_PAGE = resolve(SHARED, 'bin', 'dashboard.html');
if (!existsSync(SHARED_PAGE)) {
  console.error(
    `[esbuild] ${SHARED_PAGE} does not exist.\n`
    + '  The Codex dashboard serves the Claude Code plugin`s page; there is no second copy to\n'
    + '  fall back to. Restore it in the sibling plugin.');
  process.exit(1);
}
mkdirSync(out('bin'), { recursive: true });
copyFileSync(SHARED_PAGE, out('bin/dashboard.html'));
console.log('[esbuild] copied bin/dashboard.html from the shared plugin');
